# Site title and subtitle. This is used in _includes/header.html
title: '/docs'
subtitle: ''

# Enable/show navigation. There are there options:
#   0 - always hide
#   1 - always show
#   2 - show only if posts are present
navigation: 2

# URL to source code, used in _includes/footer.html
codeurl: 'https://github.com/kryptco/www/'

# Default categories (in order) to appear in the navigation
sections: [
    ['start', 'Get Started'],
    ['teams', 'Krypton Teams'],
    ['sigchain', 'Team Sigchain'],
    ['ssh', 'SSH Features'],
    ['security', 'Security'],
    ['use-krypton-with', 'Use with']
]

# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: '/docs'

# Dates are not included in permalinks
permalink: none

# Syntax highlighting
highlighter: rouge

# Since these are pages, it doesn't really matter
future: true

# Exclude non-site files
exclude: ['bin', 'README.md']

# Use the kramdown Markdown renderer
markdown: kramdown
    
redcarpet:
    extensions: [
        'no_intra_emphasis',
        'fenced_code_blocks',
        'autolink',
        'strikethrough',
        'superscript',
        'with_toc_data',
        'tables',
        'hardwrap'
    ]
